### PR TITLE
Async testing change

### PR DESCRIPTION
**Pull request by ArnoutD**
Base custom component testing on https://github.com/MatthewFlamm/pytest-homeassistant-custom-component

### CODE REVIEW

**Comment by ArnoutD** [comment]
ok I need to amend the .github/workflows/test.yaml

**Comment by CoMPaTech** [comment]
No you removed the local hooks, but they are still listed as excluded (but it can't find them):
  skip: [test-core-prep, test-pip-prep, testing, quality]

So if you completely remove them, you have to remove them from skip in pre-commit

pre-commit.ci is an environment that runs pre-commit for you (and potentially much quicker than pre-commit installing each run), but downside is not everything works, hence skipping all the local tests we normally do for commits.

**Comment by CoMPaTech** [comment]
Otherwise check with the smile one - otherwise I can check tomorrow

**Comment by ArnoutD** [comment]
> but downside is not everything works, hence skipping all the local tests we normally do for commits
> Otherwise check with the smile one - otherwise I can check tomorrow

It now tests inline ... so it does the test but using [pytest-homeassistant-custom-component](https://github.com/MatthewFlamm/pytest-homeassistant-custom-component) but i'll continue Thursday... I call it a night

**Pull request merged**
